classDiagram
  class Book {
    +String title
    +String author
    +Bool state
  }
  class User {
    +String name
    +String email
  }
  class Loan {
    +String start_date
    +String end_date
  }

  User "1" --> "*" Loan : makes
  Loan "1" *-- "*" Book : contains
