sequenceDiagram
    actor User
    participant Library
    Participant Book
    User->Library: Enters Building
    User->Book: Inspects Pages
    User->Library: Request Loan
    Library-->>User: loan created
